package org.example;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DBHelper {
  public static final String H2_URL = "jdbc:h2:~/test";

  private static final String CREATE_TABLES = """
          CREATE TABLE employee (
            id int NOT NULL,
            last_name varchar NULL,
            first_name varchar NULL,
            CONSTRAINT employee_pk PRIMARY KEY (id)
          );
                  	
          CREATE TABLE department (
          	id int NOT NULL,
          	department_name varchar NULL,
          	CONSTRAINT department_pk PRIMARY KEY (id)
          );
          
          CREATE TABLE employee_data (
            id int NOT NULL,
          	employee_id int NULL,
          	salary int NULL
          );
          
          CREATE TABLE employee_departments (
            id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
          	department_id int NULL,
          	employee_id int NULL
          );
          
          ALTER TABLE employee_data ADD CONSTRAINT employee_data_fk FOREIGN KEY (employee_id) REFERENCES employee(id);
          """;
  private static final String INSERT_DATA = """
          INSERT INTO employee (id, last_name, first_name) VALUES(1, 'ivanov', 'ivan');
          INSERT INTO employee (id, last_name, first_name) VALUES(2, 'petrov', 'petr');
          INSERT INTO employee (id, last_name, first_name) VALUES(3, 'ryzkova', 'oksana');
          INSERT INTO employee (id, last_name, first_name) VALUES(4, 'sergeev', 'sergey');
          
          INSERT INTO department (id, department_name) VALUES(1, 'department_1');
          INSERT INTO department (id, department_name) VALUES(2, 'department_2');
          
          INSERT INTO employee_data (id, employee_id, salary) VALUES(1, 1, 100);
          INSERT INTO employee_data (id, employee_id, salary) VALUES(2, 2, 200);
          INSERT INTO employee_data (id, employee_id, salary) VALUES(3, 3, 300);
          INSERT INTO employee_data (id, employee_id, salary) VALUES(4, 4, 400);
          
          INSERT INTO employee_departments (id, employee_id, department_id) VALUES(1, 1, 1);
          INSERT INTO employee_departments (id, employee_id, department_id) VALUES(2, 1, 2);
          INSERT INTO employee_departments (id, employee_id, department_id) VALUES(3, 2, 2);
          INSERT INTO employee_departments (id, employee_id, department_id) VALUES(4, 3, 1);
          """;
private static final String DROP_ALL_OBJECTS = "DROP ALL OBJECTS";


  public void initDb() {
    try (
            Connection c = DriverManager.getConnection(H2_URL);
            Statement s = c.createStatement();
    ) {
      s.execute(CREATE_TABLES);
      s.execute(INSERT_DATA);
    } catch (SQLException e) {
      throw new RuntimeException(e);
    }
  }

  public void dropDb() {
    try (
            Connection c = DriverManager.getConnection(H2_URL);
            Statement s = c.createStatement();
    ) {
      s.execute(DROP_ALL_OBJECTS);
    } catch (SQLException e) {
      throw new RuntimeException(e);
    }
  }
}
